// Sample data

// Data ───────────────────────────────────────────────────────────────────
export const products: Product[] = [
    // Fruits
    {
        id: 1,
        name: "Peach",
        price: 32.08,
        originalPrice: 35,
        rating: 3.8,
        reviewCount: 5,
        category: "Fruits",
        image: "https://images.unsplash.com/photo-1595079676339-1534801ad6cf?w=300&q=80",
        badges: ["In Stock", "Save 20%", "New"],
        emoji: "🍑",
    },
    {
        id: 2,
        name: "Pineapple",
        price: 60.8,
        originalPrice: 65,
        rating: 3.8,
        reviewCount: 5,
        category: "Fruits",
        image: "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=300&q=80",
        badges: ["In Stock", "Save 20%", "New"],
        emoji: "🍍",
    },
    {
        id: 3,
        name: "Rambutan",
        price: 70.8,
        originalPrice: 80,
        rating: 3.8,
        reviewCount: 5,
        category: "Fruits",
        image: "https://images.unsplash.com/photo-1611080626919-7cf5a9dbab12?w=300&q=80",
        badges: ["In Stock", "Save 20%", "New"],
        emoji: "🍈",
    },
    {
        id: 4,
        name: "Mango",
        price: 45.0,
        originalPrice: 55,
        rating: 4.5,
        reviewCount: 5,
        category: "Fruits",
        image: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=300&q=80",
        badges: ["In Stock", "Best Seller"],
        emoji: "🥭",
    },
    // Vegetables
    {
        id: 5,
        name: "Broccoli",
        price: 18.5,
        originalPrice: 22,
        rating: 4.2,
        reviewCount: 5,
        category: "Vegetables",
        image: "https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=300&q=80",
        badges: ["In Stock", "Organic"],
        emoji: "🥦",
    },
    {
        id: 6,
        name: "Carrot",
        price: 12.0,
        originalPrice: 15,
        rating: 4.0,
        reviewCount: 5,
        category: "Vegetables",
        image: "https://images.unsplash.com/photo-1447175008436-054170c2e979?w=300&q=80",
        badges: ["In Stock", "Save 20%"],
        emoji: "🥕",
    },
    {
        id: 7,
        name: "Tomato",
        price: 9.99,
        originalPrice: 13,
        rating: 4.7,
        reviewCount: 5,
        category: "Vegetables",
        image: "https://images.unsplash.com/photo-1546470427-e26264be0b11?w=300&q=80",
        badges: ["In Stock", "Fresh"],
        emoji: "🍅",
    },
    {
        id: 8,
        name: "Bell Pepper",
        price: 22.0,
        originalPrice: 28,
        rating: 3.9,
        reviewCount: 5,
        category: "Vegetables",
        image: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=300&q=80",
        badges: ["In Stock", "New"],
        emoji: "🫑",
    },
    // Bakery
    {
        id: 9,
        name: "Sourdough Bread",
        price: 38.0,
        originalPrice: 45,
        rating: 4.9,
        reviewCount: 5,
        category: "Bakery",
        image: "https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=300&q=80",
        badges: ["Fresh", "Artisan"],
        emoji: "🍞",
    },
    {
        id: 10,
        name: "Croissant",
        price: 25.5,
        originalPrice: 30,
        rating: 4.8,
        reviewCount: 5,
        category: "Bakery",
        image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=300&q=80",
        badges: ["Hot", "Save 15%"],
        emoji: "🥐",
    },
    {
        id: 11,
        name: "Blueberry Muffin",
        price: 19.0,
        originalPrice: 24,
        rating: 4.3,
        reviewCount: 5,
        category: "Bakery",
        image: "https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=300&q=80",
        badges: ["In Stock", "New"],
        emoji: "🫐",
    },
    {
        id: 12,
        name: "Cinnamon Roll",
        price: 29.9,
        originalPrice: 35,
        rating: 4.6,
        reviewCount: 5,
        category: "Bakery",
        image: "https://images.unsplash.com/photo-1509365465985-25d11c17e812?w=300&q=80",
        badges: ["Popular", "Save 10%"],
        emoji: "🌀",
    },
];

import veg from '@/assets/icons/vegetables.png'
import veg1 from '@/assets/icons/Frame 46.png'
import veg2 from '@/assets/icons/healthicons_dairy-outline.png'
import veg3 from '@/assets/icons/Group.png'
import veg4 from '@/assets/icons/mdi_meat-outline.png'
import type { Product } from '../types/productType';

export const categories = [
    { name: 'Vegetables', icon: veg },
    { name: 'Fruits', icon: veg1 },
    { name: 'Dairy & Eggs', icon: veg2 },
    { name: 'Bakery', icon: veg3 },
    { name: 'Seafood', icon: veg4 },
    { name: 'Meats', icon: veg }
];